# Generated by Django 5.2 on 2025-04-30 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logDate', models.DateTimeField(auto_now_add=True)),
                ('scrapedSource', models.CharField(max_length=255)),
                ('nbOfArticles', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('url', models.URLField(unique=True)),
                ('content', models.TextField(blank=True)),
                ('source', models.CharField(max_length=255)),
                ('date_scraped', models.DateTimeField(auto_now_add=True)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='scraper.log')),
            ],
        ),
    ]
